#!/usr/bin/env python3
"""Extracts the literal (non-loop) parameter definitions from the C# reference
XpanderTone.InitializeParameterMap and emits XpanderToneFixedParameters.inc.

Mechanical extraction guarantees data fidelity for RQ-MOD-020: names, pages,
subpages, ranges, steps, button ids, defaults and labels come verbatim from
Xplorer/Model/Tone/XpanderTone.cs. Family loops (TRACK/ENV/LFO/RAMP/MOD) are
transcribed by hand in XpanderTone.cpp because the C# builds them in loops too.

Usage: python3 juce/tools/generate_fixed_parameters.py  (from the repo root)
"""

import re
import sys

CS_PATH = "Xplorer/Model/Tone/XpanderTone.cs"
OUT_PATH = "juce/model/src/XpanderToneFixedParameters.inc"

# enum value tables used in min/max expressions of the reference
ENUMS = {
    "EnumModulationSources.KBD": 0, "EnumModulationSources.LEV2": 26,
    "EnumLFOTriggerSources.LFO1": 0, "EnumLFOTriggerSources.VIB": 5,
    "EnumLFOWaveShapes.TRIANGLE": 0, "EnumLFOWaveShapes.SAMPLE": 6,
    "EnumLFORetrigModes.OFF": 0, "EnumLFORetrigModes.EXTRIG": 3,
    "EnumVCFFilterModes._1_POLE_LOW": 0, "EnumVCFFilterModes._3_PHASE_1_LOW": 14,
    "EnumFMDestinationTypes.FMDEST_VCO": 0, "EnumFMDestinationTypes.FMDESTFM_VCF": 1,
    "EnumTriggerTypes.TRIGGER_OFF": 0, "EnumTriggerTypes.TRIGGER_EXTRIG": 3,
    "EnumModulationSourcesModMatrix.KBD": 0, "EnumModulationSourcesModMatrix.NONE": 0x1B,
}


def resolve(token: str) -> int:
    token = token.strip()
    match = re.match(r"\(int\)\(?XpanderConstants\.([A-Za-z_.0-9]+)\)?", token)
    if match:
        return ENUMS[match.group(1)]
    return int(token, 0)


def main() -> int:
    source = open(CS_PATH, encoding="utf-8").read()
    lines = source.split("\n")
    start = next(i for i, l in enumerate(lines) if "protected override void InitializeParameterMap" in l)
    end = next(i for i, l in enumerate(lines) if "GetEligibleParametersForToneMorhping" in l)
    body = "\n".join(lines[start:end])

    pattern = re.compile(
        r'_parameterMap\.Add\("([A-Z0-9_]+)",\s*'
        r"new (XpanderParameter|XpanderSignedParameter)\(\"[A-Z0-9_]+\",\s*"
        r"\(int\)XpanderConstants\.EnumPages\.([A-Z0-9_]+),\s*(0x[0-9A-Fa-f]+|\d+),\s*"
        r"([^,]+),\s*([^,]+),\s*(\d+),\s*"
        r"new SysExMessage\(new byte\[\]\s*\{([^}]+)\}\)\s*,\s*(-?\d+)(?:,\s*\"([^\"]*)\")?\s*\)\s*\);",
        re.S,
    )

    frame_template = ["0xF0", "0x10", "0x02", "0x0A", "0x00", None, "0x00", "0x00", "0x00", "0x00", "0x00", "0xF7"]
    out = [
        "// GENERATED by juce/tools/generate_fixed_parameters.py from",
        "// Xplorer/Model/Tone/XpanderTone.cs InitializeParameterMap - DO NOT EDIT.",
        "// [RQ-MOD-020] literal (non-family) parameter definitions.",
    ]
    count = 0
    for m in pattern.finditer(body):
        name, kind, page, sub, minv, maxv, step, msg, value, label = m.groups()
        raw = (msg.replace("(byte)SysExType.Start", "0xF0")
                  .replace("(byte)SysExType.Continuation", "0xF7"))
        frame = [b.strip() for b in raw.split(",")]
        if len(frame) != 12:
            print(f"unexpected frame length for {name}: {frame}", file=sys.stderr)
            return 1
        for i, byte in enumerate(frame):
            if i != 5 and byte != frame_template[i]:
                print(f"non-template byte {i}={byte} in {name}", file=sys.stderr)
                return 1
        helper = "addSigned" if kind == "XpanderSignedParameter" else "addUnsigned"
        label_cpp = f'"{label}"' if label is not None else '""'
        out.append(
            f'{helper}("{name}", EnumPages::{page}, {sub}, {resolve(minv)}, {resolve(maxv)}, '
            f'{step}, {frame[5]}, {value}, {label_cpp});'
        )
        count += 1

    out.append(f"static_assert(true); // {count} fixed parameters extracted")
    open(OUT_PATH, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"{count} fixed parameters -> {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
