#!/usr/bin/env python3
"""Generate juce/app/core/src/GeneratedSegmentFont.inc from the vendored
16-segment ASCII character map.

The VFD draws its glyphs as 16-segment shapes (ADR-JUC-023, DEC-JUC-051). The
segment *topology* — which of the 16 segments each character lights — is not
invented here: it comes from `vendor/16-Segment-ASCII_HEX-NDP.txt`, the
upstream table of dmadison/LED-Segment-ASCII (MIT, (c) 2017 David Madison),
vendored verbatim so its licence notice travels with the data and the file
stays diffable against upstream.

"NDP" = no decimal point: 16 bits per character rather than 17, which is what
this display needs — the reference VFD has no per-cell decimal point.

Bit order is upstream's, LSB first: A B C D E F G H K M N P R S T U. The
mapping from those letters to actual positions is asserted by
juce/tests/app/SegmentFontTests.cpp rather than trusted, because getting it
silently wrong would produce plausible-looking but incorrect glyphs.

Usage:
    python3 generate_segment_font.py            # writes the .inc
    python3 generate_segment_font.py --check    # exit 1 if the file is stale

[RQ-GUI-033, RQ-GUI-049, ADR-JUC-023 (DEC-JUC-051)]
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
VENDOR_PATH = HERE / "vendor" / "16-Segment-ASCII_HEX-NDP.txt"
INC_PATH = HERE.parent / "app" / "core" / "src" / "GeneratedSegmentFont.inc"

FIRST_GLYPH = 32   # ' '
LAST_GLYPH = 126   # '~'
GLYPH_COUNT = LAST_GLYPH - FIRST_GLYPH + 1

ENTRY_RE = re.compile(r"^\s*0x([0-9A-Fa-f]{4}),\s*/\*\s*(.*?)\s*\*/")
PER_ROW = 8


def parse_vendor(path: pathlib.Path) -> list[tuple[int, str]]:
    """Ordered (mask, upstream comment) pairs, one per ASCII 32..127 entry."""
    entries: list[tuple[int, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ENTRY_RE.match(line)
        if match:
            entries.append((int(match.group(1), 16), match.group(2)))
    return entries


def render(entries: list[tuple[int, str]]) -> str:
    out: list[str] = []
    out.append("// GENERATED by juce/tools/generate_segment_font.py — do not edit by hand.")
    out.append("//")
    out.append("// 16-segment lit-segment masks for printable ASCII "
               f"{FIRST_GLYPH}..{LAST_GLYPH}, indexed")
    out.append(f"// by (codePoint - {FIRST_GLYPH}). Bit 0 = segment A ... bit 15 = segment U,")
    out.append("// upstream's order; see SegmentFont.hpp for the letter -> position mapping")
    out.append("// (which SegmentFontTests.cpp pins against known glyph shapes).")
    out.append("//")
    out.append("// Source data: juce/tools/vendor/16-Segment-ASCII_HEX-NDP.txt, from")
    out.append("// github.com/dmadison/Segmented-LED-Display-ASCII")
    out.append("//   MIT License - Copyright (c) 2017 David Madison")
    out.append("//   Permission is hereby granted, free of charge, to any person obtaining a")
    out.append("//   copy of this software and associated documentation files (the")
    out.append('//   "Software"), to deal in the Software without restriction, including')
    out.append("//   without limitation the rights to use, copy, modify, merge, publish,")
    out.append("//   distribute, sublicense, and/or sell copies of the Software, and to")
    out.append("//   permit persons to whom the Software is furnished to do so, subject to")
    out.append("//   the following conditions: the above copyright notice and this")
    out.append("//   permission notice shall be included in all copies or substantial")
    out.append("//   portions of the Software.")
    out.append("//")
    out.append("// [RQ-GUI-033, RQ-GUI-049, ADR-JUC-023 (DEC-JUC-051)]")
    out.append("")
    out.append(f"inline constexpr std::array<std::uint16_t, {GLYPH_COUNT}> SEGMENT_MASKS{{{{")

    for start in range(0, GLYPH_COUNT, PER_ROW):
        chunk = entries[start:start + PER_ROW]
        cells = ", ".join(f"0x{mask:04X}" for mask, _ in chunk)
        first_char = chr(FIRST_GLYPH + start)
        last_char = chr(FIRST_GLYPH + start + len(chunk) - 1)
        legend = f"{first_char!r}..{last_char!r}".replace("'", "")
        out.append(f"    {cells},  // {legend}")

    out.append("}};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the generated file is stale")
    args = parser.parse_args()

    entries = parse_vendor(VENDOR_PATH)
    # Upstream ships 96 entries (32..127, DEL included); we keep 32..126 and
    # drop DEL, which is not printable and whose mask is zero anyway.
    if len(entries) < GLYPH_COUNT:
        sys.exit(f"{VENDOR_PATH}: expected at least {GLYPH_COUNT} entries, got {len(entries)}")
    entries = entries[:GLYPH_COUNT]

    text = render(entries)
    if args.check:
        current = INC_PATH.read_text(encoding="utf-8") if INC_PATH.exists() else ""
        if current != text:
            print(f"{INC_PATH} is stale — rerun generate_segment_font.py", file=sys.stderr)
            return 1
        print(f"{INC_PATH.name} is up to date ({GLYPH_COUNT} glyphs)")
        return 0

    INC_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {INC_PATH} ({GLYPH_COUNT} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
