#include "BackgroundRenderer.hpp"

#include "DesignTokens.hpp"
#include "SectionLayout.hpp"
#include "xplorer/app/ControlTable.hpp"

#include <functional>
#include <vector>

// Vector background painter. Every primitive below transcribes 1:1 the
// owner-validated mockup (process/2.architecture/ADR-JUC-013-mockup.svg,
// generated by ADR-JUC-013-mockup-generator.py from the geometry measured on
// the former main-background.jpg). Coordinates are in the logical canvas space
// (LOGICAL_CANVAS_WIDTH x LOGICAL_CANVAS_HEIGHT); the parent canvas transform
// scales the vector output crisply at any window size. [RQ-GUI-037, ADR-JUC-013]

namespace xplorer::app
{
    namespace
    {
        // ---- palette: now sourced from the shared design tokens (single source
        //      of truth across the whole app, not just this file). [ADR-JUC-014] --
        const juce::Colour& FRAME = tokens::semantic::diagramFrame;   // block frames / signal lines
        const juce::Colour& TITLE = tokens::semantic::diagramTitle;   // bold block/section titles
        const juce::Colour& CAPTION = tokens::semantic::diagramCaption; // parameter captions
        const juce::Colour& PLATE_TOP = tokens::semantic::panelPlateTop; // brushed-metal gradient stops
        const juce::Colour& PLATE_HI = tokens::semantic::panelPlateHi;
        const juce::Colour& PLATE_MID = tokens::semantic::panelPlateMid;
        const juce::Colour& PLATE_BOT = tokens::semantic::panelPlateBot;
        const juce::Colour& WOOD_0 = tokens::semantic::panelWood0;     // side-rail wood gradient stops
        const juce::Colour& WOOD_1 = tokens::semantic::panelWood1;
        const juce::Colour& WOOD_2 = tokens::semantic::panelWood2;
        const juce::Colour& WOOD_3 = tokens::semantic::panelWood3;
        const juce::Colour& WOOD_4 = tokens::semantic::panelWood4;
        const juce::Colour& WOOD_GRAIN = tokens::semantic::panelWoodGrain;
        // ---- geometry: appearance (stroke/radius) from tokens; layout (canvas,
        //      rail, stub) stays local — spacing scale deferred (RQ-DSN-020) ----
        // ONE width for every diagram stroke — block frames, signal lines and
        // neutral sub-panel frames alike. A draft that gave block frames their
        // own weight made the connecting wires read as the heavier element; the
        // diagram is one drawing and has one line weight. Control widgets keep
        // `strokeLine`, which is why that role still exists.
        // [RQ-GUI-051, RQ-DSN-099, ADR-JUC-027 (DEC-JUC-074)]
        constexpr float LINE_WIDTH = tokens::semantic::strokeDiagram;
        constexpr float CORNER = tokens::semantic::radiusControl;    // block corner radius
        constexpr int RAIL_WIDTH = 28;           // wood side rail
        // Cosmetic top gap (≈ the section-bar height) kept as panel material
        // (metal + wood), so the diagram does not butt against the menu bar
        // while staying visually continuous — no black band. [RQ-GUI-037]
        constexpr float CANVAS_PADDING = 5.0F;
        // The reference bitmap reserved a 32 px band at the top for the
        // WinForms menustrip; the JUCE menu bar lives outside the canvas, so
        // the band is cropped — minus the top padding kept as a black margin.
        // Diagram geometry below keeps the reference / mockup coordinates and
        // is translated up by this amount, matching the control-table shift
        // (extract_control_table.py CANVAS_TOP_CROP). [ADR-JUC-013]
        constexpr float MENUSTRIP_BAND = 32.0F;
        constexpr float CANVAS_TOP_CROP = MENUSTRIP_BAND - CANVAS_PADDING; // 27
        static_assert(static_cast<int>(CANVAS_TOP_CROP) == layout::CANVAS_TOP_CROP,
                      "SectionLayout.hpp mirrors this crop for the rhythm tests");

        /// Draw calls below are authored in the REFERENCE frame; SectionLayout.hpp
        /// states the section-bottom references in the CANVAS frame (that is the
        /// frame the control table and the rhythm rule live in). [RQ-CLR-001]
        ///
        /// Feeding this to box(), whose parameters are float, needs an explicit
        /// static_cast at the call site. Every other box() call passes int
        /// LITERALS, which MSVC converts silently; an int-typed EXPRESSION does not
        /// get that pass and raises C4244, which /WX turns into an error. Keep the
        /// casts — GCC and Clang accept the call without them, so a "cleanup" that
        /// drops them builds fine on Linux/macOS and breaks the Windows job.
        constexpr int refY(int canvasY) noexcept { return canvasY + layout::CANVAS_TOP_CROP; }

        // ---- font sizes: from the shared type scale (RQ-DSN-010). Every value
        //      is preserved exactly; consolidation (e.g. 13.5 vs 13) deferred. --
        constexpr float FS_SECTION = tokens::semantic::textTitle;    // section titles
        constexpr float FS_VCO = tokens::semantic::textDisplay;      // VCO1 / VCO2
        constexpr float FS_MIX = tokens::semantic::textSubtitle;     // MIX / LAG / LFO / RAMP
        constexpr float FS_BLOCK = tokens::semantic::textLabel;      // wide block labels
        constexpr float FS_VCA = tokens::semantic::textLabelAlt;     // VCA / VCA1
        constexpr float FS_PWM = tokens::semantic::textBody;         // PWM
        constexpr float FS_CAPTION = tokens::semantic::textCaption;  // parameter captions
        constexpr float FS_WAVE = tokens::semantic::textWave;        // TRIANGLE / SAWTOOTH / PULSE
        constexpr float FS_OUT = tokens::semantic::textSmall;        // IN/OUT labels
        constexpr float FS_SMALL = tokens::semantic::textDense;      // DESTINATION / TRIGGER IN / NOISE

        constexpr int SECTION_BAR_WIDTH = 370;
        // MOD MATRIX is the one section whose bar runs alongside a control grid,
        // so BOTH its ends come from that grid — see SectionLayout.hpp, which
        // holds them and which SectionRhythmTests checks against the real control
        // table. [RQ-GUI-062, RQ-CLR-007, ADR-JUC-034 (DEC-JUC-110)]
        // The label's baseline offset below the rule's top edge: label and rule
        // are bottom-aligned. NOT the rule's thickness — that is the measured
        // cap height, see capHeight(). No SECTION_TITLE_RISE any more: the label
        // no longer sits above the rule. [RQ-GUI-062, ADR-JUC-034 (DEC-JUC-107)]
        constexpr float SECTION_BAR_HEIGHT = tokens::component::sectionBarHeight;
        constexpr int SECTION_LABEL_GAP = tokens::component::sectionLabelGap;
        constexpr int SECTION_LEAD_STUB = tokens::component::sectionLeadStub;

        juce::Font makeFont(float size, bool bold)
        {
            juce::Font f{juce::FontOptions{size}};
            f.setBold(bold);
            return f;
        }

        // Cap height of a font, from the OUTLINE bounds of a reference capital.
        // juce::Font exposes no cap-height metric, and a GlyphArrangement's
        // bounding box is no substitute: PositionedGlyph::getBounds() reports
        // the font's full line box (`font.getHeight()`, ascent + descent), which
        // is what first made the section rule visibly taller than the label in
        // front of it. 'H' is flat-topped at the cap height and sits on the
        // baseline, so its outline height IS the cap height. Measuring one fixed
        // reference glyph — rather than each label's own ink — also keeps every
        // section rule the same height, instead of varying with whether a label
        // happens to contain a '/' or a digit.
        // [RQ-GUI-062, RQ-DSN-101, ADR-JUC-034 (DEC-JUC-109)]
        float capHeight(const juce::Font& f)
        {
            juce::GlyphArrangement reference;
            reference.addLineOfText(f, "H", 0.0F, 0.0F);
            juce::Path outline;
            reference.createPath(outline);
            return outline.getBounds().getHeight();
        }
    }

    void paintVectorBackground(juce::Graphics& g, const BlockPalette& palette)
    {
        // Functional-block identity hues: frames, fills, section labels and
        // section bars carry their block's colour so the panel reads as grouped
        // areas. Anything outside an identified block keeps FRAME. Resolved
        // from the caller-supplied runtime palette (defaults = design tokens,
        // user override wins) so the painter stays a pure function.
        // [RQ-GUI-044, RQ-DSN-092, RQ-DSN-095, ADR-JUC-018, ADR-JUC-020]
        const juce::Colour& BLK_VCO = palette.vco;
        const juce::Colour& BLK_LAG = palette.lag;
        const juce::Colour& BLK_TRACK = palette.track;
        const juce::Colour& BLK_VCF = palette.vcf;
        const juce::Colour& BLK_ENV = palette.env;
        const juce::Colour& BLK_LFO = palette.lfo;
        const juce::Colour& BLK_RAMP = palette.ramp;
        const juce::Colour& BLK_MATRIX = palette.matrix;

        const int W = LOGICAL_CANVAS_WIDTH;
        const int H = LOGICAL_CANVAS_HEIGHT;

        // Deterministic textures: a fixed seed makes every repaint identical
        // (ADR-JUC-013 §2), so the brushed/grain hairlines never shimmer.
        juce::Random rng{42};
        const auto uni = [&rng](float a, float b) { return a + (b - a) * rng.nextFloat(); };

        // ---- metal plate ---------------------------------------------------
        // Plate + wood rails fill the whole canvas (top and bottom margins
        // included) so the diagram's top/bottom gaps read as continuous panel
        // material rather than a black band cutting against the menu bar; only
        // a gentle vertical luminance gradient, no brushed streaks. [RQ-GUI-037]
        juce::ColourGradient metal{PLATE_TOP, 0.0F, 0.0F, PLATE_BOT, 0.0F, static_cast<float>(H), false};
        metal.addColour(0.25, PLATE_HI);
        metal.addColour(0.60, PLATE_MID);
        g.setGradientFill(metal);
        g.fillRect(0, 0, W, H);

        // ---- wood side rails ------------------------------------------------
        const auto paintWood = [&](int x)
        {
            juce::ColourGradient wood{WOOD_0, static_cast<float>(x), 0.0F,
                                      WOOD_4, static_cast<float>(x + RAIL_WIDTH), 0.0F, false};
            wood.addColour(0.25, WOOD_1);
            wood.addColour(0.55, WOOD_2);
            wood.addColour(0.85, WOOD_3);
            g.setGradientFill(wood);
            g.fillRect(x, 0, RAIL_WIDTH, H);

            for (int i = 0; i < 90; ++i) // grain
            {
                const float gx = static_cast<float>(x) + uni(2.0F, 26.0F);
                const float gy = uni(0.0F, static_cast<float>(H));
                const float len = uni(30.0F, 160.0F);
                const float dx = uni(-2.0F, 2.0F);
                juce::Path grain;
                grain.startNewSubPath(gx, gy);
                grain.quadraticTo(gx + dx, gy + len * 0.5F, gx, gy + len);
                g.setColour(WOOD_GRAIN.withAlpha(uni(0.15F, 0.40F)));
                g.strokePath(grain, juce::PathStrokeType{uni(0.5F, 1.6F)});
            }
            g.setColour(juce::Colours::black.withAlpha(0.45F));
            g.fillRect(x, 0, 2, H);
            g.fillRect(x + 26, 0, 2, H);
        };
        paintWood(0);
        paintWood(W - RAIL_WIDTH);

        // Everything below is diagram geometry in reference/mockup coordinates
        // (ADR-JUC-013-mockup.svg); translate it up over the cropped band.
        // Scoped so the caller's Graphics state is left untouched.
        const juce::Graphics::ScopedSaveState diagramState{g};
        g.addTransform(juce::AffineTransform::translation(0.0F, -CANVAS_TOP_CROP));

        // ---- diagram helpers ------------------------------------------------
        // Rounded joints + end caps so perpendicular segments meet with the
        // same softly-rounded corner as the block frames (drawRoundedRectangle),
        // instead of the notched butt-cap junction drawLine leaves. [RQ-GUI-037]
        const juce::PathStrokeType frameStroke{
            LINE_WIDTH, juce::PathStrokeType::curved, juce::PathStrokeType::rounded};
        // ---- paint order ----------------------------------------------------
        // The statements below stay in reading order — each block's paragraph
        // keeps its geometry together, which is the form the owner validated —
        // but they no longer paint in that order. Every primitive appends a
        // closure to one of three layers, replayed at the end as
        // lines -> boxes -> text.
        //
        // Why: a knob stub or signal line that ends ON a block edge belongs to
        // that block's paragraph, so in reading order it is drawn AFTER the
        // block and its rounded end-cap lands on top — a nub of neutral FRAME
        // colour inside the coloured fill and across the frame. Painting every
        // line first and every block over them removes the case by
        // construction. Text is a third layer because several labels are
        // emitted before their own block, and a label under a 0.30-alpha fill
        // is muddied rather than hidden — subtle enough to ship unnoticed.
        //
        // This SUPERSEDES the coloured-border re-stroke pass that used to close
        // this function (owner request, 2026-07-27): it repaired the border and
        // left the fill, which only passed while the fill was nearly invisible.
        // [RQ-GUI-051, ADR-JUC-027 (DEC-JUC-075)]
        using DrawCommand = std::function<void()>;
        std::vector<DrawCommand> lineLayer, boxLayer, textLayer;

        // A labelled block is filled with its identity hue at blockFillAlpha and
        // framed with a top-bright/bottom-dark gradient, so it reads as a slightly
        // raised plate; passing no colour keeps the neutral unfilled frame used by
        // control sub-panels. Ported 1:1 from the owner-validated mockup.
        // [RQ-GUI-044, RQ-DSN-094, ADR-JUC-018 (DEC-JUC-025/026)]
        const auto box = [&](float x, float y, float w, float h,
                             const juce::Colour* block = nullptr)
        {
            boxLayer.push_back([&g, x, y, w, h, block]
            {
                if (block != nullptr)
                {
                    g.setColour(block->withAlpha(tokens::component::blockFillAlpha));
                    g.fillRoundedRectangle(x, y, w, h, CORNER);
                    juce::ColourGradient relief{*block, x, y,
                                                block->darker(tokens::component::blockFrameRelief),
                                                x, y + h, false};
                    g.setGradientFill(relief);
                }
                else
                {
                    g.setColour(FRAME);
                }
                g.drawRoundedRectangle(x, y, w, h, CORNER, LINE_WIDTH);
            });
        };
        const auto line = [&](float x1, float y1, float x2, float y2)
        {
            lineLayer.push_back([&g, &frameStroke, x1, y1, x2, y2]
            {
                g.setColour(FRAME);
                juce::Path segment;
                segment.startNewSubPath(x1, y1);
                segment.lineTo(x2, y2);
                g.strokePath(segment, frameStroke);
            });
        };
        // A control tick: drops from a block's bottom edge onto the control it
        // feeds, and STOPS on the first pixel that control paints. Both helpers
        // take the target's own canvas-frame top rather than a length, because a
        // length is what let the two drift apart — SectionLayout.hpp derives the
        // end, and BackgroundRendererTests pins every row against the real
        // control table. [RQ-GUI-071, ADR-JUC-027 (DEC-JUC-112)]
        const auto knobTick = [&](float cx, int fromY, int knobCanvasTopY)
        {
            line(cx, static_cast<float>(fromY), cx, layout::knobTickEndReferenceY(knobCanvasTopY));
        };
        const auto comboTick = [&](float cx, int fromY, int comboCanvasTopY)
        {
            line(cx, static_cast<float>(fromY), cx, layout::comboTickEndReferenceY(comboCanvasTopY));
        };
        const auto text = [&](int x, int y, const juce::String& s, float size, bool bold,
                              juce::Colour colour, juce::Justification just)
        {
            textLayer.push_back([&g, x, y, s, size, bold, colour, just]
            {
                g.setColour(colour);
                g.setFont(makeFont(size, bold));
                g.drawSingleLineText(s, x, y, just);
            });
        };
        const auto caption = [&](int x, int y, const juce::String& s)
        {
            text(x, y, s, FS_CAPTION, false, CAPTION, juce::Justification::horizontallyCentred);
        };
        // Section header: label + separator bar, both in the owning block's hue —
        // replacing the single blue gradient formerly shared by every section.
        // Flat bar with a left-to-right fade (bright at the label end), no
        // vertical shading. [RQ-GUI-037, RQ-GUI-044, ADR-JUC-018 (DEC-JUC-027)]
        //
        // The label sits ON the rule, not above it: the rule keeps its right end
        // but is INTERRUPTED by the label instead of running under it, and the
        // two are aligned on their BOTTOM edges (the labels are all caps, so the
        // baseline is the bottom of the letters). That frees ~11 px of header
        // height per section without moving anything else, and is why the label
        // must be measured — the stacked layout never needed its width.
        //
        // Left to right: a short lead-in stub, a gap, the label, a gap, then the
        // rest of the rule out to its unchanged right end — the Xpander's own
        // silkscreen treatment, where the rule runs into the section name rather
        // than starting after it. The rule is as tall as the label's capitals,
        // so it reads as a band level with the letters, not an underline.
        // [RQ-GUI-062, ADR-JUC-034 (DEC-JUC-107)]
        const auto section = [&](int x, int y, const juce::String& s, const juce::Colour& block,
                                 int barWidth = SECTION_BAR_WIDTH)
        {
            const auto baselineY = y + static_cast<int>(SECTION_BAR_HEIGHT);
            const auto labelFont = makeFont(FS_SECTION, true);
            // Width: GlyphArrangement, not the deprecated Font::getStringWidthFloat.
            // Height: capHeight(), NOT this arrangement's bounding box — see capHeight().
            const auto labelX = static_cast<float>(x + SECTION_LEAD_STUB + SECTION_LABEL_GAP);
            const auto barX = labelX + juce::GlyphArrangement::getStringWidth(labelFont, s)
                              + SECTION_LABEL_GAP;
            const auto barEnd = static_cast<float>(x + barWidth);
            const auto barHeight = capHeight(labelFont);
            const auto barY = static_cast<float>(baselineY) - barHeight;

            text(static_cast<int>(labelX), baselineY, s, FS_SECTION, true, block,
                 juce::Justification::left);
            textLayer.push_back([&g, x, barX, barEnd, barY, barHeight, block]
            {
                // Lead-in stub: flat block hue at full opacity, the same colour as
                // the label and as the first pixel of the run after it, so the
                // three read as one interrupted rule. Only the run AFTER the
                // label carries the fade.
                // [RQ-GUI-062, ADR-JUC-034 (DEC-JUC-108)]
                g.setColour(block);
                g.fillRect(static_cast<float>(x), barY,
                           static_cast<float>(SECTION_LEAD_STUB), barHeight);

                juce::ColourGradient bar{block, barX, barY,
                                         block.withAlpha(tokens::component::sectionBarFadeEnd),
                                         barEnd, barY, false};
                g.setGradientFill(bar);
                g.fillRect(barX, barY, barEnd - barX, barHeight);
            });
        };
        const auto outLabel = [&](int x, int y, const juce::String& l1, const juce::String& l2)
        {
            line(static_cast<float>(x), static_cast<float>(y), static_cast<float>(x + 14), static_cast<float>(y));
            text(x + 19, y - 2, l1, FS_OUT, true, TITLE, juce::Justification::left);
            text(x + 19, y + 10, l2, FS_OUT, true, TITLE, juce::Justification::left);
        };
        const auto smallLabel = [&](int x, int y, const juce::String& s,
                                    juce::Justification just = juce::Justification::right)
        {
            text(x, y, s, FS_SMALL, true, CAPTION, just);
        };
        const auto blockTitle = [&](int x, int y, const juce::String& s, float size,
                                    juce::Justification just = juce::Justification::horizontallyCentred)
        {
            text(x, y, s, size, true, TITLE, just);
        };

        // ================================================= LEFT COLUMN =======
        // --- VCO1 group
        box(51, 32, 147, 52, &BLK_VCO);
        blockTitle(64, 63, "VCO1", FS_VCO, juce::Justification::left);
        blockTitle(193, 49, "TRIANGLE", FS_WAVE, juce::Justification::right);
        blockTitle(193, 61, "SAWTOOTH", FS_WAVE, juce::Justification::right);
        blockTitle(193, 74, "PULSE", FS_WAVE, juce::Justification::right);
        line(198, 45, 330, 45);
        line(198, 57, 330, 57);
        line(198, 70, 234, 70);
        line(286, 70, 330, 70);
        box(234, 60, 52, 23, &BLK_VCO);
        blockTitle(260, 76, "PWM", FS_PWM);
        knobTick(259, 83, layout::KNOB_ROW_TOP_CANVAS_Y); // VCO1_PW
        box(330, 32, 53, 52, &BLK_VCO);
        blockTitle(356, 63, "MIX", FS_MIX);
        line(383, 58, 405, 58);
        box(405, 45, 53, 26, &BLK_VCO);
        blockTitle(431, 63, "VCA", FS_VCA);
        knobTick(432, 71, layout::KNOB_ROW_TOP_CANVAS_Y); // VCO1_VOLUME
        knobTick(82, 84, layout::KNOB_ROW_TOP_CANVAS_Y);  // VCO1_FREQ
        knobTick(170, 84, layout::KNOB_ROW_TOP_CANVAS_Y); // VCO1_DETUNE
        caption(82, 137, "FREQUENCY");
        caption(170, 137, "DETUNE");
        caption(259, 137, "PULSE WIDTH");
        caption(432, 137, "VOLUME");
        // VCO1 VCA out -> straight into the VCF left edge
        line(458, 58, 525, 58);
        // FM modulation buses (both at y=180): left branch ends on the VCO1
        // FREQUENCY stub, right branch ends on the VCF FREQ stub.
        line(40, 88, 82, 88);
        line(40, 88, 40, 180);
        line(40, 180, 284, 180);
        // DESTINATION -> up to the VCO1 bus
        line(276, 220, 284, 220);
        line(284, 220, 284, 180);
        // DESTINATION -> right bus, hopping over the x=499 vertical, up into VCF FREQ
        line(276, 230, 289, 230);
        line(289, 230, 289, 180);
        line(289, 180, 492, 180);
        lineLayer.push_back([&g, &frameStroke]
        {
            juce::Path hop; // semicircular bump over x=499 (SVG arc M492 180 A7 7 0 0 1 506 180)
            hop.startNewSubPath(492.0F, 180.0F);
            hop.quadraticTo(499.0F, 166.0F, 506.0F, 180.0F);
            g.setColour(FRAME);
            g.strokePath(hop, frameStroke);
        });
        line(506, 180, 513, 180);
        line(513, 180, 513, 82);
        line(513, 82, 541, 82);

        // --- FM / VCO2 group
        box(51, 210, 102, 36, &BLK_VCO);
        blockTitle(102, 233, "FM VCA", FS_BLOCK);
        box(184, 210, 90, 52);
        text(229, 274, "DESTINATION", FS_SMALL, true, CAPTION, juce::Justification::horizontallyCentred);
        line(153, 228, 184, 228);
        knobTick(106, 246, layout::KNOB_ROW_FM_CANVAS_Y); // FM_AMP
        caption(106, 300, "FM AMPLITUDE");
        box(329, 210, 52, 52, &BLK_VCO);
        blockTitle(355, 241, "MIX", FS_MIX);
        line(381, 232, 405, 232);
        box(405, 220, 53, 26, &BLK_VCO);
        blockTitle(431, 238, "VCA", FS_VCA);
        knobTick(430, 246, layout::KNOB_ROW_VCO2_VCA_CANVAS_Y); // VCO2_VOLUME
        // VCO2-row VCA out -> right, then up at x=499 into the VCF
        line(458, 232, 499, 232);
        line(499, 232, 499, 70);
        lineLayer.push_back([&g, &frameStroke]
        {
            juce::Path curve; // SVG M499 70 Q499 58 509 58
            curve.startNewSubPath(499.0F, 70.0F);
            curve.quadraticTo(499.0F, 58.0F, 509.0F, 58.0F);
            g.setColour(FRAME);
            g.strokePath(curve, frameStroke);
        });
        caption(430, 314, "VOLUME");
        box(51, 310, 147, 52, &BLK_VCO);
        blockTitle(64, 341, "VCO2", FS_VCO, juce::Justification::left);
        blockTitle(193, 324, "TRIANGLE", FS_WAVE, juce::Justification::right);
        blockTitle(193, 338, "SAWTOOTH", FS_WAVE, juce::Justification::right);
        blockTitle(193, 352, "PULSE", FS_WAVE, juce::Justification::right);
        // vco2 waves route up into MIX
        line(198, 320, 297, 320);
        line(297, 320, 297, 228);
        line(297, 228, 329, 228);
        line(198, 334, 303, 334);
        line(303, 334, 303, 237);
        line(303, 237, 329, 237);
        line(198, 348, 233, 348);
        box(233, 340, 52, 23, &BLK_VCO);
        blockTitle(259, 356, "PWM", FS_PWM);
        knobTick(260, 363, layout::KNOB_ROW_VCO2_CANVAS_Y); // VCO2_PW
        line(285, 348, 309, 348);
        line(309, 348, 309, 246);
        line(309, 246, 329, 246);
        // The rotation must live INSIDE the deferred closure: text() no longer
        // paints where it is called, so a ScopedSaveState wrapped around the
        // call would be popped long before the text layer is replayed.
        // [ADR-JUC-027 (DEC-JUC-075)]
        textLayer.push_back([&g]
        {
            juce::Graphics::ScopedSaveState state{g};
            g.addTransform(juce::AffineTransform::rotation(
                -juce::MathConstants<float>::halfPi, 318.0F, 300.0F));
            g.setColour(CAPTION);
            g.setFont(makeFont(FS_SMALL, true));
            g.drawSingleLineText("NOISE", 318, 300, juce::Justification::left);
        });
        line(317, 255, 329, 255);
        line(317, 255, 317, 270);
        knobTick(82, 362, layout::KNOB_ROW_VCO2_CANVAS_Y);  // VCO2_FREQ
        knobTick(169, 362, layout::KNOB_ROW_VCO2_CANVAS_Y); // VCO2_DETUNE
        caption(82, 418, "FREQUENCY");
        caption(169, 418, "DETUNE");
        caption(260, 418, "PULSE WIDTH");
        // FM carrier: VCO2 TRIANGLE tap up at x=204 to the y=305 run into FM VCA
        line(40, 229, 40, 305);
        line(40, 229, 51, 229);
        line(40, 305, 204, 305);
        line(204, 305, 204, 320);
        // Terminator for the VCO group: sectionGapAbove below the VCO2 MOD tick-box
        // row (canvas y 426), i.e. baseline 442 -> anchor 442 + 23. The +23 is the
        // constant relating a section() anchor to its label baseline in canvas
        // space: -CANVAS_TOP_CROP (27) + int(SECTION_BAR_HEIGHT) (4).
        // [RQ-CLR-001, ADR-CLR-001 (DEC-CLR-001-C)]
        section(layout::SECTION_X_LEFT, layout::SECTION_VCO_Y, "VCO1/VCO2/FM", BLK_VCO);

        // --- LAG   (whole group +13 canvas px, RQ-CLR-004: equalises this column's
        //            two below-separator gaps at 45 and 46 px)
        box(81, static_cast<float>(refY(layout::LAG_FRAME_TOP_CANVAS_Y)), 268, 36, &BLK_LAG);
        blockTitle(215, 537, "LAG", FS_MIX);
        outLabel(349, 531, "LAG", "OUT");
        line(52, 531, 81, 531);
        line(52, 531, 52, 576);
        // Left-aligned with the LAG_IN combo (x=35), 9 px below it. [RQ-GUI-037]
        smallLabel(35, 589, "LAG IN", juce::Justification::left);
        knobTick(215, 550, layout::KNOB_ROW_LAG_CANVAS_Y); // FMLAG_RATE
        caption(215, refY(layout::LAG_RATE_CAPTION_BASELINE_CANVAS_Y), "RATE");
        // RATE's baseline (canvas 576) is this section's lowest visible element —
        // lower than the EXPO/LEGATO row at 572. [RQ-CLR-001]
        section(layout::SECTION_X_LEFT, layout::SECTION_LAG_Y, "LAG", BLK_LAG);

        // --- TRACKING GENERATOR   (whole group +21 canvas px: TRACK X is pinned by
        //                           RQ-CLR-003, so the group moves to meet it)
        box(81, 700, 268, 36, &BLK_TRACK);
        blockTitle(215, 723, "TRACKING GENERATOR", FS_BLOCK);
        outLabel(349, 717, "TRACK", "OUT");
        line(52, 717, 81, 717);
        line(52, 717, 52, 762);
        // Left-aligned with the TRACK_X_IN combo (x=35), same 9 px offset as LAG IN.
        smallLabel(35, 775, "TRACK IN", juce::Justification::left);
        {
            const int centres[] = {126, 170, 214, 258, 302}; // PT knob centres (table)
            for (int i = 0; i < 5; ++i)
            {
                knobTick(static_cast<float>(centres[i]), 736, layout::KNOB_ROW_TRACK_CANVAS_Y);
                caption(centres[i], refY(layout::TRACK_PT_CAPTION_BASELINE_CANVAS_Y),
                        "PT " + juce::String(i + 1));
            }
        }
        // Unchanged: shares one baseline with RAMP X and MOD MATRIX. [RQ-CLR-003]
        section(layout::SECTION_X_LEFT, layout::SECTION_TRACK_Y, "TRACK X", BLK_TRACK);

        // ================================================= CENTER COLUMN =====
        // --- VCF/VCA chain
        box(525, 45, 186, 26, &BLK_VCF);
        blockTitle(618, 63, "MULTIMODE VCF", FS_BLOCK);
        box(729, 45, 62, 26, &BLK_VCF);
        blockTitle(760, 63, "VCA1", FS_VCA);
        box(804, 45, 62, 26, &BLK_VCF);
        blockTitle(835, 63, "VCA", FS_VCA);
        line(711, 58, 729, 58);
        line(791, 58, 804, 58);
        outLabel(866, 58, "VOICE", "OUT");
        knobTick(541, 71, layout::KNOB_ROW_TOP_CANVAS_Y); // VCF_FREQ
        knobTick(591, 71, layout::KNOB_ROW_TOP_CANVAS_Y); // VCF_RES
        comboTick(layout::COMBO_VCF_MODE_CENTRE_X, 71, layout::COMBO_VCF_MODE_CANVAS_Y);
        knobTick(759, 71, layout::KNOB_ROW_TOP_CANVAS_Y); // VCF_VCA1_VOLUME
        knobTick(834, 71, layout::KNOB_ROW_TOP_CANVAS_Y); // VCF_VCA2_VOLUME
        caption(541, 137, "FREQ");
        caption(591, 137, "RES");
        // Moves with its tick: leaving the caption on the old x would trade one
        // misalignment for another, this time between the tick and the words
        // under it. [RQ-GUI-071]
        caption(layout::captionCentreX(layout::COMBO_VCF_MODE_CENTRE_X), 137, "MODE (15)");
        caption(759, 137, "VOLUME");
        caption(834, 137, "VOLUME");
        section(layout::SECTION_X_CENTRE, layout::SECTION_VCF_Y, "VCF/VCA", BLK_VCF);

        // --- ENV
        box(525, 242, 267, 26, &BLK_ENV);
        blockTitle(658, 260, "ENVELOPE GENERATOR", FS_BLOCK);
        box(804, 242, 63, 26, &BLK_ENV);
        blockTitle(835, 260, "VCA", FS_VCA);
        line(792, 255, 804, 255);
        outLabel(867, 255, "ENV", "OUT");
        // TRIGGER IN: into the ENV block and down into the trigger frame below
        line(514, 255, 525, 255);
        line(514, 255, 514, 351);
        line(514, 351, 524, 351);
        smallLabel(508, 363, "TRIGGER");
        smallLabel(508, 373, "IN");
        {
            const int centres[] = {541, 591, 641, 691, 750, 835}; // knob centres (table)
            for (int cx : centres)
            {
                knobTick(static_cast<float>(cx), 268, layout::KNOB_ROW_ENV_CANVAS_Y);
            }
        }
        caption(541, 320, "DELAY");
        caption(591, 320, "ATTACK");
        caption(641, 320, "DECAY");
        caption(691, 320, "SUSTAIN");
        caption(750, 320, "RELEASE");
        caption(835, 320, "VOLUME");
        box(524, 329, 373, 42);
        section(layout::SECTION_X_CENTRE, layout::SECTION_ENV_Y, "ENV X", BLK_ENV);

        // --- LFO
        box(524, 475, 269, 26, &BLK_LFO);
        blockTitle(658, 493, "LFO", FS_MIX);
        box(804, 475, 63, 26, &BLK_LFO);
        blockTitle(835, 493, "VCA", FS_VCA);
        line(793, 488, 804, 488);
        outLabel(867, 488, "LFO", "OUT");
        {
            const int centres[] = {546, 759, 834}; // SPEED/RETRIG/AMPLITUDE knob centres (table)
            for (int cx : centres)
            {
                knobTick(static_cast<float>(cx), 501, layout::KNOB_ROW_LFO_CANVAS_Y);
            }
        }
        // WAVESHAPE is a combo, not a knob, so it leaves the loop: different top
        // inset, and a different centre. The loop used to carry it at 657 and
        // call that "the combo centre" in its own comment — the combo is
        // (611, 100) wide, so its centre is 661. [RQ-GUI-071]
        comboTick(layout::COMBO_LFO_WAVE_CENTRE_X, 501, layout::COMBO_LFO_WAVE_CANVAS_Y);
        caption(546, 554, "SPEED");
        caption(layout::captionCentreX(layout::COMBO_LFO_WAVE_CENTRE_X), 554, "WAVESHAPE");
        caption(759, 554, "RETRIG");
        caption(834, 554, "AMPLITUDE");
        section(layout::SECTION_X_CENTRE, layout::SECTION_LFO_Y, "LFO X", BLK_LFO);

        // --- RAMP
        box(524, 658, 266, 26, &BLK_RAMP);
        blockTitle(656, 676, "RAMP", FS_MIX);
        outLabel(790, 671, "RAMP", "OUT");
        line(514, 671, 524, 671);
        line(514, 671, 514, 770);
        line(514, 770, 524, 770);
        smallLabel(508, 779, "TRIGGER");
        smallLabel(508, 789, "IN");
        knobTick(657, 684, layout::KNOB_ROW_RAMP_CANVAS_Y); // RAMP_X_RATE
        caption(657, 738, "RATE");
        box(524, static_cast<float>(refY(layout::RAMP_TRIGGER_FRAME_TOP_CANVAS_Y)), 374,
            static_cast<float>(layout::RAMP_TRIGGER_FRAME_HEIGHT));
        section(layout::SECTION_X_CENTRE, layout::SECTION_RAMP_Y, "RAMP X", BLK_RAMP);

        // ================================================= RIGHT =============
        // "MOD MATRIX", not "MODULATION MATRIX": at 17 characters the full name
        // was twice the length of every other section label, and with the bar
        // now starting after the label it left this section almost no bar at
        // all. [RQ-GUI-062, ADR-JUC-034 (DEC-JUC-108)]
        section(layout::SECTION_X_MATRIX, layout::SECTION_MATRIX_Y, "MOD MATRIX", BLK_MATRIX,
                layout::SECTION_MATRIX_BAR_WIDTH);

        // Nothing above has painted yet: replay the layers in paint order, so a
        // signal line can never land on the block it runs into.
        // [RQ-GUI-051, ADR-JUC-027 (DEC-JUC-075)]
        for (const auto& drawLine : lineLayer)
            drawLine();
        for (const auto& drawBox : boxLayer)
            drawBox();
        for (const auto& drawText : textLayer)
            drawText();
    }
}
