#include "BackgroundRenderer.hpp"

#include "DesignTokens.hpp"
#include "xplorer/app/ControlTable.hpp"

// Vector background painter. Every primitive below transcribes 1:1 the
// owner-validated mockup (process/2.architecture/ADR-JUC-013-mockup.svg,
// generated by ADR-JUC-013-mockup-generator.py from the geometry measured on
// the former main-background.jpg). Coordinates are in the logical canvas space
// (LOGICAL_CANVAS_WIDTH x LOGICAL_CANVAS_HEIGHT); the parent canvas transform
// scales the vector output crisply at any window size. [RQ-GUI-037, ADR-JUC-013]

namespace xplorer::app
{
    namespace
    {
        // ---- palette: now sourced from the shared design tokens (single source
        //      of truth across the whole app, not just this file). [ADR-JUC-014] --
        const juce::Colour& FRAME = tokens::semantic::diagramFrame;   // block frames / signal lines
        const juce::Colour& TITLE = tokens::semantic::diagramTitle;   // bold block/section titles
        const juce::Colour& CAPTION = tokens::semantic::diagramCaption; // parameter captions
        const juce::Colour& PLATE_TOP = tokens::semantic::panelPlateTop; // brushed-metal gradient stops
        const juce::Colour& PLATE_HI = tokens::semantic::panelPlateHi;
        const juce::Colour& PLATE_MID = tokens::semantic::panelPlateMid;
        const juce::Colour& PLATE_BOT = tokens::semantic::panelPlateBot;
        const juce::Colour& WOOD_0 = tokens::semantic::panelWood0;     // side-rail wood gradient stops
        const juce::Colour& WOOD_1 = tokens::semantic::panelWood1;
        const juce::Colour& WOOD_2 = tokens::semantic::panelWood2;
        const juce::Colour& WOOD_3 = tokens::semantic::panelWood3;
        const juce::Colour& WOOD_4 = tokens::semantic::panelWood4;
        const juce::Colour& WOOD_GRAIN = tokens::semantic::panelWoodGrain;
        const juce::Colour& BAR_TOP = tokens::semantic::sectionBarTop; // section underline gradient
        const juce::Colour& BAR_MID = tokens::semantic::sectionBarMid;
        const juce::Colour& BAR_BOT = tokens::semantic::sectionBarBot;

        // ---- geometry: appearance (stroke/radius) from tokens; layout (canvas,
        //      rail, stub) stays local — spacing scale deferred (RQ-DSN-020) ----
        constexpr float LINE_WIDTH = tokens::semantic::strokeLine;   // frames + signal lines
        constexpr float CORNER = tokens::semantic::radiusControl;    // block corner radius
        constexpr int STUB_LENGTH = 12;          // default control-tick length
        constexpr int RAIL_WIDTH = 28;           // wood side rail
        // Cosmetic top gap (≈ the section-bar height) kept as panel material
        // (metal + wood), so the diagram does not butt against the menu bar
        // while staying visually continuous — no black band. [RQ-GUI-037]
        constexpr float CANVAS_PADDING = 5.0F;
        // The reference bitmap reserved a 32 px band at the top for the
        // WinForms menustrip; the JUCE menu bar lives outside the canvas, so
        // the band is cropped — minus the top padding kept as a black margin.
        // Diagram geometry below keeps the reference / mockup coordinates and
        // is translated up by this amount, matching the control-table shift
        // (extract_control_table.py CANVAS_TOP_CROP). [ADR-JUC-013]
        constexpr float MENUSTRIP_BAND = 32.0F;
        constexpr float CANVAS_TOP_CROP = MENUSTRIP_BAND - CANVAS_PADDING; // 27

        // ---- font sizes: from the shared type scale (RQ-DSN-010). Every value
        //      is preserved exactly; consolidation (e.g. 13.5 vs 13) deferred. --
        constexpr float FS_SECTION = tokens::semantic::textTitle;    // section titles
        constexpr float FS_VCO = tokens::semantic::textDisplay;      // VCO1 / VCO2
        constexpr float FS_MIX = tokens::semantic::textSubtitle;     // MIX / LAG / LFO / RAMP
        constexpr float FS_BLOCK = tokens::semantic::textLabel;      // wide block labels
        constexpr float FS_VCA = tokens::semantic::textLabelAlt;     // VCA / VCA1
        constexpr float FS_PWM = tokens::semantic::textBody;         // PWM
        constexpr float FS_CAPTION = tokens::semantic::textCaption;  // parameter captions
        constexpr float FS_WAVE = tokens::semantic::textWave;        // TRIANGLE / SAWTOOTH / PULSE
        constexpr float FS_OUT = tokens::semantic::textSmall;        // IN/OUT labels
        constexpr float FS_SMALL = tokens::semantic::textDense;      // DESTINATION / TRIGGER IN / NOISE

        constexpr int SECTION_BAR_WIDTH = 370;
        constexpr float SECTION_BAR_HEIGHT = 4.5F;
        constexpr int SECTION_TITLE_RISE = 7;    // title baseline above the bar

        juce::Font makeFont(float size, bool bold)
        {
            juce::Font f{juce::FontOptions{size}};
            f.setBold(bold);
            return f;
        }
    }

    void paintVectorBackground(juce::Graphics& g)
    {
        const int W = LOGICAL_CANVAS_WIDTH;
        const int H = LOGICAL_CANVAS_HEIGHT;

        // Deterministic textures: a fixed seed makes every repaint identical
        // (ADR-JUC-013 §2), so the brushed/grain hairlines never shimmer.
        juce::Random rng{42};
        const auto uni = [&rng](float a, float b) { return a + (b - a) * rng.nextFloat(); };

        // ---- metal plate ---------------------------------------------------
        // Plate + wood rails fill the whole canvas (top and bottom margins
        // included) so the diagram's top/bottom gaps read as continuous panel
        // material rather than a black band cutting against the menu bar; only
        // a gentle vertical luminance gradient, no brushed streaks. [RQ-GUI-037]
        juce::ColourGradient metal{PLATE_TOP, 0.0F, 0.0F, PLATE_BOT, 0.0F, static_cast<float>(H), false};
        metal.addColour(0.25, PLATE_HI);
        metal.addColour(0.60, PLATE_MID);
        g.setGradientFill(metal);
        g.fillRect(0, 0, W, H);

        // ---- wood side rails ------------------------------------------------
        const auto paintWood = [&](int x)
        {
            juce::ColourGradient wood{WOOD_0, static_cast<float>(x), 0.0F,
                                      WOOD_4, static_cast<float>(x + RAIL_WIDTH), 0.0F, false};
            wood.addColour(0.25, WOOD_1);
            wood.addColour(0.55, WOOD_2);
            wood.addColour(0.85, WOOD_3);
            g.setGradientFill(wood);
            g.fillRect(x, 0, RAIL_WIDTH, H);

            for (int i = 0; i < 90; ++i) // grain
            {
                const float gx = static_cast<float>(x) + uni(2.0F, 26.0F);
                const float gy = uni(0.0F, static_cast<float>(H));
                const float len = uni(30.0F, 160.0F);
                const float dx = uni(-2.0F, 2.0F);
                juce::Path grain;
                grain.startNewSubPath(gx, gy);
                grain.quadraticTo(gx + dx, gy + len * 0.5F, gx, gy + len);
                g.setColour(WOOD_GRAIN.withAlpha(uni(0.15F, 0.40F)));
                g.strokePath(grain, juce::PathStrokeType{uni(0.5F, 1.6F)});
            }
            g.setColour(juce::Colours::black.withAlpha(0.45F));
            g.fillRect(x, 0, 2, H);
            g.fillRect(x + 26, 0, 2, H);
        };
        paintWood(0);
        paintWood(W - RAIL_WIDTH);

        // Everything below is diagram geometry in reference/mockup coordinates
        // (ADR-JUC-013-mockup.svg); translate it up over the cropped band.
        // Scoped so the caller's Graphics state is left untouched.
        const juce::Graphics::ScopedSaveState diagramState{g};
        g.addTransform(juce::AffineTransform::translation(0.0F, -CANVAS_TOP_CROP));

        // ---- diagram helpers ------------------------------------------------
        // Rounded joints + end caps so perpendicular segments meet with the
        // same softly-rounded corner as the block frames (drawRoundedRectangle),
        // instead of the notched butt-cap junction drawLine leaves. [RQ-GUI-037]
        const juce::PathStrokeType frameStroke{
            LINE_WIDTH, juce::PathStrokeType::curved, juce::PathStrokeType::rounded};
        const auto box = [&](float x, float y, float w, float h)
        {
            g.setColour(FRAME);
            g.drawRoundedRectangle(x, y, w, h, CORNER, LINE_WIDTH);
        };
        const auto line = [&](float x1, float y1, float x2, float y2)
        {
            g.setColour(FRAME);
            juce::Path segment;
            segment.startNewSubPath(x1, y1);
            segment.lineTo(x2, y2);
            g.strokePath(segment, frameStroke);
        };
        const auto stub = [&](int cx, int y, int len = STUB_LENGTH)
        {
            line(static_cast<float>(cx), static_cast<float>(y),
                 static_cast<float>(cx), static_cast<float>(y + len));
        };
        const auto text = [&](int x, int y, const juce::String& s, float size, bool bold,
                              juce::Colour colour, juce::Justification just)
        {
            g.setColour(colour);
            g.setFont(makeFont(size, bold));
            g.drawSingleLineText(s, x, y, just);
        };
        const auto caption = [&](int x, int y, const juce::String& s)
        {
            text(x, y, s, FS_CAPTION, false, CAPTION, juce::Justification::horizontallyCentred);
        };
        const auto section = [&](int x, int y, const juce::String& s, int barWidth = SECTION_BAR_WIDTH)
        {
            text(x, y - SECTION_TITLE_RISE, s, FS_SECTION, true, TITLE, juce::Justification::left);
            // Flat solid bar with a left-to-right luminance gradient (bright at
            // the label end, fading right) — no vertical shading, which read as
            // an over-rounded tube. Same blue palette. [RQ-GUI-037]
            juce::ColourGradient bar{BAR_TOP, static_cast<float>(x), static_cast<float>(y),
                                     BAR_BOT, static_cast<float>(x + barWidth), static_cast<float>(y), false};
            bar.addColour(0.5, BAR_MID);
            g.setGradientFill(bar);
            g.fillRect(static_cast<float>(x), static_cast<float>(y),
                       static_cast<float>(barWidth), SECTION_BAR_HEIGHT);
        };
        const auto outLabel = [&](int x, int y, const juce::String& l1, const juce::String& l2)
        {
            line(static_cast<float>(x), static_cast<float>(y), static_cast<float>(x + 14), static_cast<float>(y));
            text(x + 19, y - 2, l1, FS_OUT, true, TITLE, juce::Justification::left);
            text(x + 19, y + 10, l2, FS_OUT, true, TITLE, juce::Justification::left);
        };
        const auto smallLabel = [&](int x, int y, const juce::String& s,
                                    juce::Justification just = juce::Justification::right)
        {
            text(x, y, s, FS_SMALL, true, CAPTION, just);
        };
        const auto blockTitle = [&](int x, int y, const juce::String& s, float size,
                                    juce::Justification just = juce::Justification::horizontallyCentred)
        {
            text(x, y, s, size, true, TITLE, just);
        };

        // ================================================= LEFT COLUMN =======
        // --- VCO1 group
        box(51, 32, 147, 52);
        blockTitle(64, 63, "VCO1", FS_VCO, juce::Justification::left);
        blockTitle(193, 49, "TRIANGLE", FS_WAVE, juce::Justification::right);
        blockTitle(193, 61, "SAWTOOTH", FS_WAVE, juce::Justification::right);
        blockTitle(193, 74, "PULSE", FS_WAVE, juce::Justification::right);
        line(198, 45, 330, 45);
        line(198, 57, 330, 57);
        line(198, 70, 234, 70);
        line(286, 70, 330, 70);
        box(234, 60, 52, 23);
        blockTitle(260, 76, "PWM", FS_PWM);
        stub(259, 83);
        box(330, 32, 53, 52);
        blockTitle(356, 63, "MIX", FS_MIX);
        line(383, 58, 405, 58);
        box(405, 45, 53, 26);
        blockTitle(431, 63, "VCA", FS_VCA);
        stub(432, 71, 23); // VCO1_VOLUME centre
        stub(82, 84);
        stub(170, 84);
        caption(82, 137, "FREQUENCY");
        caption(170, 137, "DETUNE");
        caption(259, 137, "PULSE WIDTH");
        caption(432, 137, "VOLUME");
        // VCO1 VCA out -> straight into the VCF left edge
        line(458, 58, 525, 58);
        // FM modulation buses (both at y=180): left branch ends on the VCO1
        // FREQUENCY stub, right branch ends on the VCF FREQ stub.
        line(40, 88, 82, 88);
        line(40, 88, 40, 180);
        line(40, 180, 284, 180);
        // DESTINATION -> up to the VCO1 bus
        line(276, 220, 284, 220);
        line(284, 220, 284, 180);
        // DESTINATION -> right bus, hopping over the x=499 vertical, up into VCF FREQ
        line(276, 230, 289, 230);
        line(289, 230, 289, 180);
        line(289, 180, 492, 180);
        {
            juce::Path hop; // semicircular bump over x=499 (SVG arc M492 180 A7 7 0 0 1 506 180)
            hop.startNewSubPath(492.0F, 180.0F);
            hop.quadraticTo(499.0F, 166.0F, 506.0F, 180.0F);
            g.setColour(FRAME);
            g.strokePath(hop, frameStroke);
        }
        line(506, 180, 513, 180);
        line(513, 180, 513, 82);
        line(513, 82, 541, 82);

        // --- FM / VCO2 group
        box(51, 210, 102, 36);
        blockTitle(102, 233, "FM VCA", FS_BLOCK);
        box(184, 210, 90, 52);
        text(229, 274, "DESTINATION", FS_SMALL, true, CAPTION, juce::Justification::horizontallyCentred);
        line(153, 228, 184, 228);
        stub(106, 246);
        caption(106, 300, "FM AMPLITUDE");
        box(329, 210, 52, 52);
        blockTitle(355, 241, "MIX", FS_MIX);
        line(381, 232, 405, 232);
        box(405, 220, 53, 26);
        blockTitle(431, 238, "VCA", FS_VCA);
        stub(430, 246, 24); // VCO2_VOLUME centre
        // VCO2-row VCA out -> right, then up at x=499 into the VCF
        line(458, 232, 499, 232);
        line(499, 232, 499, 70);
        {
            juce::Path curve; // SVG M499 70 Q499 58 509 58
            curve.startNewSubPath(499.0F, 70.0F);
            curve.quadraticTo(499.0F, 58.0F, 509.0F, 58.0F);
            g.setColour(FRAME);
            g.strokePath(curve, frameStroke);
        }
        caption(430, 314, "VOLUME");
        box(51, 310, 147, 52);
        blockTitle(64, 341, "VCO2", FS_VCO, juce::Justification::left);
        blockTitle(193, 324, "TRIANGLE", FS_WAVE, juce::Justification::right);
        blockTitle(193, 338, "SAWTOOTH", FS_WAVE, juce::Justification::right);
        blockTitle(193, 352, "PULSE", FS_WAVE, juce::Justification::right);
        // vco2 waves route up into MIX
        line(198, 320, 297, 320);
        line(297, 320, 297, 228);
        line(297, 228, 329, 228);
        line(198, 334, 303, 334);
        line(303, 334, 303, 237);
        line(303, 237, 329, 237);
        line(198, 348, 233, 348);
        box(233, 340, 52, 23);
        blockTitle(259, 356, "PWM", FS_PWM);
        stub(260, 363); // VCO2_PW centre
        line(285, 348, 309, 348);
        line(309, 348, 309, 246);
        line(309, 246, 329, 246);
        {
            juce::Graphics::ScopedSaveState state{g};
            g.addTransform(juce::AffineTransform::rotation(
                -juce::MathConstants<float>::halfPi, 318.0F, 300.0F));
            text(318, 300, "NOISE", FS_SMALL, true, CAPTION, juce::Justification::left);
        }
        line(317, 255, 329, 255);
        line(317, 255, 317, 270);
        stub(82, 362);
        stub(169, 362); // VCO2_DETUNE centre
        caption(82, 418, "FREQUENCY");
        caption(169, 418, "DETUNE");
        caption(260, 418, "PULSE WIDTH");
        // FM carrier: VCO2 TRIANGLE tap up at x=204 to the y=305 run into FM VCA
        line(40, 229, 40, 305);
        line(40, 229, 51, 229);
        line(40, 305, 204, 305);
        line(204, 305, 204, 320);
        section(53, 487, "VCO1/VCO2/FM");

        // --- LAG
        box(81, 501, 268, 36);
        blockTitle(215, 524, "LAG", FS_MIX);
        outLabel(349, 518, "LAG", "OUT");
        line(52, 518, 81, 518);
        line(52, 518, 52, 563);
        // Left-aligned with the LAG_IN combo (x=35), 9 px below it. [RQ-GUI-037]
        smallLabel(35, 576, "LAG IN", juce::Justification::left);
        stub(215, 537);
        caption(215, 590, "RATE");
        section(53, 629, "LAG");

        // --- TRACKING GENERATOR
        box(81, 679, 268, 36);
        blockTitle(215, 702, "TRACKING GENERATOR", FS_BLOCK);
        outLabel(349, 696, "TRACK", "OUT");
        line(52, 696, 81, 696);
        line(52, 696, 52, 741);
        // Left-aligned with the TRACK_X_IN combo (x=35), same 9 px offset as LAG IN.
        smallLabel(35, 754, "TRACK IN", juce::Justification::left);
        {
            const int centres[] = {126, 170, 214, 258, 302}; // PT knob centres (table)
            for (int i = 0; i < 5; ++i)
            {
                stub(centres[i], 715);
                caption(centres[i], 766, "PT " + juce::String(i + 1));
            }
        }
        section(53, 799, "TRACK X");

        // ================================================= CENTER COLUMN =====
        // --- VCF/VCA chain
        box(525, 45, 186, 26);
        blockTitle(618, 63, "MULTIMODE VCF", FS_BLOCK);
        box(729, 45, 62, 26);
        blockTitle(760, 63, "VCA1", FS_VCA);
        box(804, 45, 62, 26);
        blockTitle(835, 63, "VCA", FS_VCA);
        line(711, 58, 729, 58);
        line(791, 58, 804, 58);
        outLabel(866, 58, "VOICE", "OUT");
        stub(541, 71, 24);
        stub(591, 71, 24);
        stub(669, 71, 24);
        stub(759, 71, 24);
        stub(834, 71, 24);
        caption(541, 137, "FREQ");
        caption(591, 137, "RES");
        caption(669, 137, "MODE (15)");
        caption(759, 137, "VOLUME");
        caption(834, 137, "VOLUME");
        section(526, 194, "VCF/VCA");

        // --- ENV
        box(525, 242, 267, 26);
        blockTitle(658, 260, "ENVELOPE GENERATOR", FS_BLOCK);
        box(804, 242, 63, 26);
        blockTitle(835, 260, "VCA", FS_VCA);
        line(792, 255, 804, 255);
        outLabel(867, 255, "ENV", "OUT");
        // TRIGGER IN: into the ENV block and down into the trigger frame below
        line(514, 255, 525, 255);
        line(514, 255, 514, 351);
        line(514, 351, 524, 351);
        smallLabel(508, 363, "TRIGGER");
        smallLabel(508, 373, "IN");
        {
            const int centres[] = {541, 591, 641, 691, 750, 835}; // knob centres (table)
            for (int cx : centres)
            {
                stub(cx, 268);
            }
        }
        caption(541, 320, "DELAY");
        caption(591, 320, "ATTACK");
        caption(641, 320, "DECAY");
        caption(691, 320, "SUSTAIN");
        caption(750, 320, "RELEASE");
        caption(835, 320, "VOLUME");
        box(524, 329, 373, 42);
        section(526, 416, "ENV X");

        // --- LFO
        box(524, 467, 269, 26);
        blockTitle(658, 485, "LFO", FS_MIX);
        box(804, 467, 63, 26);
        blockTitle(835, 485, "VCA", FS_VCA);
        line(793, 480, 804, 480);
        outLabel(867, 480, "LFO", "OUT");
        {
            // SPEED/RETRIG/AMP knob centres (table); 657 = WAVESHAPE combo centre.
            const int centres[] = {546, 657, 759, 834};
            for (int cx : centres)
            {
                stub(cx, 493);
            }
        }
        caption(546, 546, "SPEED");
        caption(657, 546, "WAVESHAPE");
        caption(759, 546, "RETRIG");
        caption(834, 546, "AMPLITUDE");
        section(527, 597, "LFO X");

        // --- RAMP
        box(524, 646, 266, 26);
        blockTitle(656, 664, "RAMP", FS_MIX);
        outLabel(790, 659, "RAMP", "OUT");
        line(514, 659, 524, 659);
        line(514, 659, 514, 758);
        line(514, 758, 524, 758);
        smallLabel(508, 767, "TRIGGER");
        smallLabel(508, 777, "IN");
        stub(657, 672);
        caption(657, 726, "RATE");
        box(524, 734, 374, 41);
        section(527, 799, "RAMP X");

        // ================================================= RIGHT =============
        section(958, 799, "MODULATION MATRIX", 268);
    }
}
